version: '3.9'
services:
  redis:
    container_name: redis_container
    image: bitnami/redis:latest
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '6379:6379'