name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  K8_AVAILABLE: false
  NUMBER_OF_RECORDS: 100000

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install dependencies
        run: npm install

      - name: remove existing input.json
        run: rm ./input.json
      
      - name: generate input data
        run: node ./generator/generator.js

      - name: parse data
        run: npm run start


      

      

  